### ISSUE TITLE
Help With A Tweak To Game Streaming Page

### ISSUE THREAD

**Issue by dinosaw** [xjackk/TwitchTVExpose#7]
Heyo, I gotta say, this is exactly what I've been looking for. Browsing Twitch streams on the actual Twitch site is so frustrating and sometimes causes my browser to crash. This is so, so much more clean and slim that even when I load the most popular browsing games that I don't run into ANY issues at all. So let me open by thanking you for this! Very, very much appreciated.

Now basically what I'd like to do is make a small tweak to the page that lists all the streamers for a particular game. As of right now, it shows the thumbnail of the stream, the title of the stream under that, and then the amount of viewers under that. What I'd like to do is replace the thumbnail of the stream with the streamer's avatar (or even just add the streamer's avatar someone on the page). And possibly just add the username of the streamer either above or under the viewer total.

Is this something you could help me out with? Any help would be greatly appreciated. And thanks again for this awesome project!

**Comment by xjackk** [comment]
@dinosaw Glad you dig the project.

I am doing private consulting work currently, plus I am back at university. I am a bit busy.

Any questions you have feel free to email me. I would like to push you in the right direction. I will respond with detail. 

~ cheers
